# Generated by Django 2.0.7 on 2018-07-20 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supervisr_core', '0004_auto_20180617_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebApplication',
            fields=[
                ('useracquirable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supervisr_core.UserAcquirable')),
                ('name', models.TextField()),
                ('upstream', models.URLField()),
                ('access_slug', models.SlugField()),
                ('add_remote_user', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('supervisr_core.useracquirable',),
        ),
    ]
