# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFiles',
            fields=[
                ('BaseId', models.AutoField(primary_key=True, serialize=False)),
                ('BaseJobId', models.IntegerField()),
                ('JobId', models.IntegerField()),
                ('FileId', models.BigIntegerField()),
                ('FileIndex', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CDImages',
            fields=[
                ('MediaId', models.IntegerField(primary_key=True, serialize=False)),
                ('LastBurn', models.DateTimeField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ClientId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(unique=True)),
                ('Uname', models.TextField()),
                ('AutoPrune', models.IntegerField(blank=True, null=True)),
                ('FileRetention', models.BigIntegerField(blank=True, null=True)),
                ('JobRetention', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('Counter', models.TextField(primary_key=True, serialize=False)),
                ('MinValue', models.IntegerField(blank=True, null=True)),
                ('MaxValue', models.IntegerField(blank=True, null=True)),
                ('CurrentValue', models.IntegerField(blank=True, null=True)),
                ('WrapCounter', models.TextField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('DeviceId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField()),
                ('MediaTypeId', models.IntegerField(blank=True, null=True)),
                ('StorageId', models.IntegerField(blank=True, null=True)),
                ('DevMounts', models.IntegerField(blank=True, null=True)),
                ('DevReadBytes', models.BigIntegerField(blank=True, null=True)),
                ('DevWriteBytes', models.BigIntegerField(blank=True, null=True)),
                ('DevReadBytesSinceCleaning', models.BigIntegerField(blank=True, null=True)),
                ('DevWriteBytesSinceCleaning', models.BigIntegerField(blank=True, null=True)),
                ('DevReadTime', models.BigIntegerField(blank=True, null=True)),
                ('DevWriteTime', models.BigIntegerField(blank=True, null=True)),
                ('DevReadTimeSinceCleaning', models.BigIntegerField(blank=True, null=True)),
                ('DevWriteTimeSinceCleaning', models.BigIntegerField(blank=True, null=True)),
                ('CleaningDate', models.DateTimeField(blank=True, null=True)),
                ('CleaningPeriod', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('FileId', models.BigAutoField(primary_key=True, serialize=False)),
                ('FileIndex', models.IntegerField(blank=True, null=True)),
                ('JobId', models.IntegerField()),
                ('PathId', models.IntegerField()),
                ('FilenameId', models.IntegerField()),
                ('DeltaSeq', models.SmallIntegerField(blank=True, null=True)),
                ('MarkId', models.IntegerField(blank=True, null=True)),
                ('LStat', models.TextField()),
                ('MD5', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Filename',
            fields=[
                ('FilenameId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileSet',
            fields=[
                ('FileSetId', models.AutoField(primary_key=True, serialize=False)),
                ('FileSet', models.TextField()),
                ('MD5', models.TextField(blank=True, null=True)),
                ('CreateTime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('JobId', models.AutoField(primary_key=True, serialize=False)),
                ('Job', models.TextField()),
                ('Name', models.TextField()),
                ('Type', models.CharField(max_length=1)),
                ('Level', models.CharField(max_length=1)),
                ('ClientId', models.IntegerField(blank=True, null=True)),
                ('JobStatus', models.CharField(max_length=1)),
                ('SchedTime', models.DateTimeField(blank=True, null=True)),
                ('StartTime', models.DateTimeField(blank=True, null=True)),
                ('EndTime', models.DateTimeField(blank=True, null=True)),
                ('RealEndTime', models.DateTimeField(blank=True, null=True)),
                ('JobTDate', models.BigIntegerField(blank=True, null=True)),
                ('VolSessionId', models.IntegerField(blank=True, null=True)),
                ('VolSessionTime', models.IntegerField(blank=True, null=True)),
                ('JobFiles', models.IntegerField(blank=True, null=True)),
                ('JobBytes', models.BigIntegerField(blank=True, null=True)),
                ('ReadBytes', models.BigIntegerField(blank=True, null=True)),
                ('JobErrors', models.IntegerField(blank=True, null=True)),
                ('JobMissingFiles', models.IntegerField(blank=True, null=True)),
                ('PoolId', models.IntegerField(blank=True, null=True)),
                ('FileSetId', models.IntegerField(blank=True, null=True)),
                ('PriorJobId', models.IntegerField(blank=True, null=True)),
                ('PurgedFiles', models.IntegerField(blank=True, null=True)),
                ('HasBase', models.IntegerField(blank=True, null=True)),
                ('HasCache', models.IntegerField(blank=True, null=True)),
                ('Reviewed', models.IntegerField(blank=True, null=True)),
                ('Comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobHisto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobId', models.IntegerField()),
                ('Job', models.TextField()),
                ('Name', models.TextField()),
                ('Type', models.CharField(max_length=1)),
                ('Level', models.CharField(max_length=1)),
                ('ClientId', models.IntegerField(blank=True, null=True)),
                ('JobStatus', models.CharField(max_length=1)),
                ('SchedTime', models.DateTimeField(blank=True, null=True)),
                ('StartTime', models.DateTimeField(blank=True, null=True)),
                ('EndTime', models.DateTimeField(blank=True, null=True)),
                ('RealEndTime', models.DateTimeField(blank=True, null=True)),
                ('JobTDate', models.BigIntegerField(blank=True, null=True)),
                ('VolSessionId', models.IntegerField(blank=True, null=True)),
                ('VolSessionTime', models.IntegerField(blank=True, null=True)),
                ('JobFiles', models.IntegerField(blank=True, null=True)),
                ('JobBytes', models.BigIntegerField(blank=True, null=True)),
                ('ReadBytes', models.BigIntegerField(blank=True, null=True)),
                ('JobErrors', models.IntegerField(blank=True, null=True)),
                ('JobMissingFiles', models.IntegerField(blank=True, null=True)),
                ('PoolId', models.IntegerField(blank=True, null=True)),
                ('FileSetId', models.IntegerField(blank=True, null=True)),
                ('PriorJobId', models.IntegerField(blank=True, null=True)),
                ('PurgedFiles', models.IntegerField(blank=True, null=True)),
                ('HasBase', models.IntegerField(blank=True, null=True)),
                ('HasCache', models.IntegerField(blank=True, null=True)),
                ('Reviewed', models.IntegerField(blank=True, null=True)),
                ('Comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobMedia',
            fields=[
                ('JobMediaId', models.AutoField(primary_key=True, serialize=False)),
                ('JobId', models.IntegerField()),
                ('MediaId', models.IntegerField()),
                ('FirstIndex', models.IntegerField(blank=True, null=True)),
                ('LastIndex', models.IntegerField(blank=True, null=True)),
                ('StartFile', models.IntegerField(blank=True, null=True)),
                ('EndFile', models.IntegerField(blank=True, null=True)),
                ('StartBlock', models.IntegerField(blank=True, null=True)),
                ('EndBlock', models.IntegerField(blank=True, null=True)),
                ('VolIndex', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('LocationId', models.AutoField(primary_key=True, serialize=False)),
                ('Location', models.TextField()),
                ('Cost', models.IntegerField(blank=True, null=True)),
                ('Enabled', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocationLog',
            fields=[
                ('LocLogId', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('Comment', models.TextField()),
                ('MediaId', models.IntegerField(blank=True, null=True)),
                ('LocationId', models.IntegerField(blank=True, null=True)),
                ('NewVolStatus', models.CharField(max_length=9)),
                ('NewEnabled', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('LogId', models.AutoField(primary_key=True, serialize=False)),
                ('JobId', models.IntegerField(blank=True, null=True)),
                ('Time', models.DateTimeField(blank=True, null=True)),
                ('LogText', models.TextField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('MediaId', models.AutoField(primary_key=True, serialize=False)),
                ('VolumeName', models.TextField(unique=True)),
                ('Slot', models.IntegerField(blank=True, null=True)),
                ('PoolId', models.IntegerField(blank=True, null=True)),
                ('MediaType', models.TextField()),
                ('MediaTypeId', models.IntegerField(blank=True, null=True)),
                ('LabelType', models.IntegerField(blank=True, null=True)),
                ('FirstWritten', models.DateTimeField(blank=True, null=True)),
                ('LastWritten', models.DateTimeField(blank=True, null=True)),
                ('LabelDate', models.DateTimeField(blank=True, null=True)),
                ('VolJobs', models.IntegerField(blank=True, null=True)),
                ('VolFiles', models.IntegerField(blank=True, null=True)),
                ('VolBlocks', models.IntegerField(blank=True, null=True)),
                ('VolMounts', models.IntegerField(blank=True, null=True)),
                ('VolBytes', models.BigIntegerField(blank=True, null=True)),
                ('VolParts', models.IntegerField(blank=True, null=True)),
                ('VolErrors', models.IntegerField(blank=True, null=True)),
                ('VolWrites', models.BigIntegerField(blank=True, null=True)),
                ('VolCapacityBytes', models.BigIntegerField(blank=True, null=True)),
                ('VolStatus', models.CharField(max_length=9)),
                ('Enabled', models.IntegerField(blank=True, null=True)),
                ('Recycle', models.IntegerField(blank=True, null=True)),
                ('ActionOnPurge', models.IntegerField(blank=True, null=True)),
                ('VolRetention', models.BigIntegerField(blank=True, null=True)),
                ('VolUseDuration', models.BigIntegerField(blank=True, null=True)),
                ('MaxVolJobs', models.IntegerField(blank=True, null=True)),
                ('MaxVolFiles', models.IntegerField(blank=True, null=True)),
                ('MaxVolBytes', models.BigIntegerField(blank=True, null=True)),
                ('InChanger', models.IntegerField(blank=True, null=True)),
                ('StorageId', models.IntegerField(blank=True, null=True)),
                ('DeviceId', models.IntegerField(blank=True, null=True)),
                ('MediaAddressing', models.IntegerField(blank=True, null=True)),
                ('VolReadTime', models.BigIntegerField(blank=True, null=True)),
                ('VolWriteTime', models.BigIntegerField(blank=True, null=True)),
                ('EndFile', models.IntegerField(blank=True, null=True)),
                ('EndBlock', models.IntegerField(blank=True, null=True)),
                ('LocationId', models.IntegerField(blank=True, null=True)),
                ('RecycleCount', models.IntegerField(blank=True, null=True)),
                ('InitialWrite', models.DateTimeField(blank=True, null=True)),
                ('ScratchPoolId', models.IntegerField(blank=True, null=True)),
                ('RecyclePoolId', models.IntegerField(blank=True, null=True)),
                ('Comment', models.TextField(blank=True, null=True)),
                ('VolABytes', models.BigIntegerField(blank=True, null=True)),
                ('VolAPadding', models.BigIntegerField(blank=True, null=True)),
                ('VolHoleBytes', models.BigIntegerField(blank=True, null=True)),
                ('VolHoles', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('MediaTypeId', models.AutoField(primary_key=True, serialize=False)),
                ('MediaType', models.TextField()),
                ('ReadOnly', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('PathId', models.AutoField(primary_key=True, serialize=False)),
                ('Path', models.TextField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PathHierarchy',
            fields=[
                ('PathId', models.IntegerField(primary_key=True, serialize=False)),
                ('PPathId', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PathVisibility',
            fields=[
                ('PathId', models.IntegerField()),
                ('JobId', models.IntegerField(primary_key=True, serialize=False)),
                ('Size', models.BigIntegerField(blank=True, null=True)),
                ('Files', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PathVisibility',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('PoolId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(unique=True)),
                ('NumVols', models.IntegerField(blank=True, null=True)),
                ('MaxVols', models.IntegerField(blank=True, null=True)),
                ('UseOnce', models.IntegerField(blank=True, null=True)),
                ('UseCatalog', models.IntegerField(blank=True, null=True)),
                ('AcceptAnyVolume', models.IntegerField(blank=True, null=True)),
                ('VolRetention', models.BigIntegerField(blank=True, null=True)),
                ('VolUseDuration', models.BigIntegerField(blank=True, null=True)),
                ('MaxVolJobs', models.IntegerField(blank=True, null=True)),
                ('MaxVolFiles', models.IntegerField(blank=True, null=True)),
                ('MaxVolBytes', models.BigIntegerField(blank=True, null=True)),
                ('AutoPrune', models.IntegerField(blank=True, null=True)),
                ('Recycle', models.IntegerField(blank=True, null=True)),
                ('ActionOnPurge', models.IntegerField(blank=True, null=True)),
                ('PoolType', models.CharField(max_length=9)),
                ('LabelType', models.IntegerField(blank=True, null=True)),
                ('LabelFormat', models.TextField(blank=True, null=True)),
                ('Enabled', models.IntegerField(blank=True, null=True)),
                ('ScratchPoolId', models.IntegerField(blank=True, null=True)),
                ('RecyclePoolId', models.IntegerField(blank=True, null=True)),
                ('NextPoolId', models.IntegerField(blank=True, null=True)),
                ('MigrationHighBytes', models.BigIntegerField(blank=True, null=True)),
                ('MigrationLowBytes', models.BigIntegerField(blank=True, null=True)),
                ('MigrationTime', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RestoreObject',
            fields=[
                ('RestoreObjectId', models.AutoField(primary_key=True, serialize=False)),
                ('ObjectName', models.TextField()),
                ('RestoreObject', models.TextField()),
                ('PluginName', models.TextField()),
                ('ObjectLength', models.IntegerField(blank=True, null=True)),
                ('ObjectFullLength', models.IntegerField(blank=True, null=True)),
                ('ObjectIndex', models.IntegerField(blank=True, null=True)),
                ('ObjectType', models.IntegerField(blank=True, null=True)),
                ('FileIndex', models.IntegerField(blank=True, null=True)),
                ('JobId', models.IntegerField()),
                ('ObjectCompression', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('SnapshotId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField()),
                ('JobId', models.IntegerField(blank=True, null=True)),
                ('FileSetId', models.IntegerField(blank=True, null=True)),
                ('CreateTDate', models.BigIntegerField()),
                ('CreateDate', models.DateTimeField()),
                ('ClientId', models.IntegerField(blank=True, null=True)),
                ('Volume', models.TextField()),
                ('Device', models.TextField()),
                ('Type', models.TextField()),
                ('Retention', models.IntegerField(blank=True, null=True)),
                ('Comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('JobStatus', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('JobStatusLong', models.TextField(blank=True, null=True)),
                ('Severity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('StorageId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField()),
                ('AutoChanger', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnsavedFiles',
            fields=[
                ('UnsavedId', models.AutoField(primary_key=True, serialize=False)),
                ('JobId', models.IntegerField()),
                ('PathId', models.IntegerField()),
                ('FilenameId', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VersionId', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
