# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 23:00
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0033_baseprovider_baseproviderinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamecheapProviderInstance',
            fields=[
                ('baseproviderinstance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseProviderInstance')),
                ('api_key', models.TextField()),
                ('api_username', models.TextField()),
                ('username', models.TextField()),
                ('sandbox', models.BooleanField(default=True)),
            ],
            bases=('core.baseproviderinstance',),
        ),
    ]
