# Generated by Django 2.0.3 on 2018-03-28 18:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_mod_beacon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulse',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pulse',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
