# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 18:48
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_dns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsrecord',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dnsrecord',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
