# Global Variables
before_script:
  - "python3 -m pip install -U virtualenv"
  - "virtualenv env"
  - "source env/bin/activate"
  - "pip install -U -r requirements.txt -r requirements-dev.txt"
stages:
  - test
  - test-db
  - build-release
  - deploy
image: python:3.6
variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE: supervisr_test
  MYSQL_ROOT_PASSWORD: 'EK-5jnKfjrGRm<77'
  SUPERVISR_LOCAL_SETTINGS: supervisr.local_settings_mysql
services:
# - redis:latest
  - mysql:latest

# All normal tests
coverage:
  except:
    - prod
  script:
    - "inv ci.coverage"
  stage: test
  cache:
    paths:
      - env/
pip_install:
  except:
    - prod
  script:
    - "deactivate"
    - "virtualenv env"
    - "source env/bin/activate"
    - "pip install git+${CI_REPOSITORY_URL}#egg=supervisr"
    - "cp -R ./env/lib/python*/site-packages/supervisr/mod/_seed/* ."
    - "python manage.py migrate"
isort:
  except:
    - prod
  script:
    - "inv ci.isort"
  stage: test
  cache:
    paths:
      - env/
migrations:
  except:
    - prod
  script:
    - "inv supervisr.migrate"
  stage: test
  cache:
    paths:
      - env/
pyroma:
  except:
    - prod
  script:
    - "inv ci.pyroma"
  stage: test
  cache:
    paths:
      - env/
prospector:
  except:
    - prod
  script:
    - "inv ci.prospector"
  stage: test
  cache:
    paths:
      - env/
pylint:
  except:
    - prod
  script:
    - "inv ci.lint"
  stage: test
  cache:
    paths:
      - env/
unittest:
  except:
    - prod
  script:
    - "inv ci.unittest"
  stage: test
  cache:
    paths:
      - env/

# Release test
bundle_release:
  before_script:
    - ''
  image: debian:stable
  script:
    - apt install -y libncurses5-dev libglib2.0-dev libgeoip-dev libtokyocabinet-dev zlib1g-dev libncursesw5-dev build-essential libbz2-dev dh-autoreconf dh-python dh-systemd dh-virtualenv dpkg-dev debhelper dh-exec
    - dpkg-buildpackage -us -uc
  only:
    - tags
  stage: build-release

# Deploy
deploy:
  before_script: []
  services: []
  environment:
    name: production
    url: "https://my.beryju.org"
  only:
    - prod
  script:
    - "eval $(ssh-agent -s)"
    - "mkdir ~/.ssh -p"
    - "echo \"${CI_SSH_PRIVATE}\" | ssh-add -"
    - "ssh -o 'StrictHostKeyChecking=no' beryjuorg@ory1-web-prod-1.ory1.beryju.org \"./update_supervisr.sh\""
  stage: deploy
