before_script:
  - sudo apt-get update >/dev/null
  - sudo apt-get -y install python3-pip python3-dev libsasl2-dev libldap2-dev libssl-dev python3-mysqldb >/dev/null
  - sudo python3 -m pip install -U -r requirements.txt >/dev/null
stages:
  - test
test:
  script:
    - cd supervisr/
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - python3 manage.py test
  type: test
  stage: test

