before_script:
  - sudo apt-get update >/dev/null
  - sudo apt-get -y install python3-pip python3-dev libsasl2-dev libldap2-dev libssl-dev python3-mysqldb libmysqlclient-dev >/dev/null
  - sudo python3 -m pip install -U virtualenv
  - virtualenv env
  - source env/bin/activate
  - pip3 install invoke
  - inv install --dev
stages:
  - test
  - deploy
migrations:
  type: test
  stage: test
  script:
    - inv migrate
unittest:
  type: test
  stage: test
  script:
    - inv unittest
coverage:
  type: test
  stage: test
  script:
    - inv coverage
isort:
  type: test
  stage: test
  script:
    - inv isort
pylint:
  type: test
  stage: test
  script:
    - inv lint
prospector:
  type: test
  stage: test
  script:
    - inv prospector
deploy:
  type: deploy
  stage: deploy
  only:
    - prod
  script:
    - "eval $(ssh-agent -s)"
    - "mkdir ~/.ssh -p"
    - "echo \"${CI_SSH_PRIVATE}\" | ssh-add -"
    - inv deploy --user=beryjuorg --fqdn=ory1-web-prod-1.ory1.beryju.org
  environment:
    name: production
    url: https://my.beryju.org
