before_script:
  - sudo apt-get update >/dev/null
  - sudo apt-get -y install python3-pip python3-dev libsasl2-dev libldap2-dev libssl-dev python3-mysqldb libmysqlclient-dev >/dev/null
  - sudo python3 -m pip install -U invoke
  - sudo inv install --dev
stages:
  - test
  - deploy
migrations:
  type: test
  stage: test
  script:
    - python3 manage.py makemigrations
    - python3 manage.py migrate
unittest:
  type: test
  stage: test
  script:
    - python3 manage.py test --pattern=Test*.py
coverage:
  type: test
  stage: test
  script:
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - coverage run --source='.' manage.py test --pattern=Test*.py
    - coverage report
isort:
  type: test
  stage: test
  script:
    - isort -c -vb
pylint:
  type: test
  stage: test
  script:
    - pylint --load-plugins pylint_django supervisr*
prospector:
  type: test
  stage: test
  script:
    - prospector -I migration
deploy:
  type: deploy
  stage: deploy
  only:
    - prod
  script:
    - "eval $(ssh-agent -s)"
    - "mkdir ~/.ssh -p"
    - "echo \"${CI_SSH_PRIVATE}\" | ssh-add -"
    - inv deploy
  environment:
    name: production
    url: https://my.beryju.org
