fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.1
    hooks:
      - id: check-ast
      - id: check-json
      - id: mixed-line-ending
        args: ['--fix=auto']
      - id: name-tests-test
        args: ['--django']
      - id: trailing-whitespace
  - repo: git@github.com:coldnight/pre-commit-pylint.git
    sha: v0.0.2
    hooks:
    -   id: pylint-py3k
    -   id: pylint-score-limit
        args:
        - --rcfile=./.pylintrc
