strictness: medium
test-warnings: true
doc-warnings: false

ignore-paths:
  - env
  - migrations
  - docs
  - node_modules

uses:
 - django

pylint:
  disable:
     - redefined-outer-name
     - arguments-differ
     - no-self-use
     - cyclic-import
     - fixme
     - locally-disabled