# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_puppet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppetmodulerelease',
            name='metadata',
            field=models.TextField(blank=True),
        ),
    ]
