# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr/puppet', '0005_auto_20170423_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppetmodulerelease',
            name='release',
            field=models.FileField(max_length=500, upload_to=''),
        ),
    ]
