# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 12:17
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supervisr', '0010_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailAccount',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supervisr.Product')),
                ('address', models.CharField(max_length=64)),
                ('quota', models.BigIntegerField(default=0)),
                ('can_send', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=128)),
            ],
            bases=('supervisr.product',),
        ),
        migrations.CreateModel(
            name='MailDomain',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supervisr.Product')),
                ('domain_mail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supervisr.Domain')),
            ],
            bases=('supervisr.product',),
        ),
    ]
