# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_mail', '0008_auto_20170325_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='maildomain',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
