# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 12:23
from __future__ import unicode_literals

import supervisr.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('ipaddress_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='ServerCPU',
            fields=[
                ('cpu_id', models.AutoField(primary_key=True, serialize=False)),
                ('cores', models.IntegerField()),
                ('smt', models.BooleanField()),
                ('make', models.TextField()),
                ('model', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServerDrive',
            fields=[
                ('drive_id', models.AutoField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('make', models.TextField()),
                ('model', models.TextField()),
                ('rpm', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServerNIC',
            fields=[
                ('nic_id', models.AutoField(primary_key=True, serialize=False)),
                ('speed', models.IntegerField()),
                ('ips', models.ManyToManyField(to='supervisr.IPAddress')),
            ],
        ),
        migrations.CreateModel(
            name='ServerProduct',
            fields=[
                ('server_id', models.AutoField(primary_key=True, serialize=False)),
                ('ram', models.IntegerField()),
                ('is_virtual', models.BooleanField(default=True)),
                ('is_managed', models.BooleanField(default=True)),
                ('cpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisr.ServerCPU')),
                ('drives', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisr.ServerDrive')),
                ('nics', models.ManyToManyField(to='supervisr.ServerNIC')),
            ],
            bases=(supervisr.models.Product, models.Model),
        ),
    ]
