# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr', '0003_serverproduct_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servernic',
            name='ips',
            field=models.ManyToManyField(blank=True, to='supervisr.IPAddress'),
        ),
    ]
