# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import supervisr.models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr', '0005_accountconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountconfirmation',
            name='expires',
            field=models.BigIntegerField(default=supervisr.models.expiry_date, editable=False),
        ),
    ]
