# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr', '0005_auto_20161231_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value_json', models.TextField()),
            ],
        ),
    ]
