# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr', '0007_remove_serverproduct_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servernic',
            name='ips',
        ),
        migrations.RemoveField(
            model_name='serverproduct',
            name='cpus',
        ),
        migrations.RemoveField(
            model_name='serverproduct',
            name='drives',
        ),
        migrations.RemoveField(
            model_name='serverproduct',
            name='nics',
        ),
        migrations.DeleteModel(
            name='IPAddress',
        ),
        migrations.DeleteModel(
            name='ServerCPU',
        ),
        migrations.DeleteModel(
            name='ServerDrive',
        ),
        migrations.DeleteModel(
            name='ServerNIC',
        ),
        migrations.DeleteModel(
            name='ServerProduct',
        ),
    ]
