# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr', '0009_auto_20170112_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supervisr.Product')),
                ('domain_name', models.CharField(max_length=255)),
                ('registrar', models.TextField()),
                ('is_sub', models.BooleanField(default=False)),
            ],
            bases=('supervisr.product',),
        ),
    ]
