# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 18:07
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import supervisr.models

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supervisr', '0011_auto_20170112_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('glyph', models.CharField(default='envelope', max_length=200)),
                ('message', models.TextField()),
                ('current', models.BooleanField(default=True)),
                ('action_required', models.BooleanField(default=True)),
                ('action_view', models.TextField()),
                ('action_parmas_json', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('closed_date', models.DateTimeField(auto_now=True)),
                ('invoker', models.ForeignKey(default=supervisr.models.get_system_user, on_delete=django.db.models.deletion.CASCADE, related_name='events_invoked', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
