# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 18:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import supervisr.models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr', '0013_auto_20170112_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='action_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='invoker',
            field=models.ForeignKey(default=supervisr.models.get_system_user, on_delete=django.db.models.deletion.CASCADE, related_name='events_invoked', to=settings.AUTH_USER_MODEL),
        ),
    ]
