# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 20:16
from __future__ import unicode_literals

from django.db import migrations, models

import supervisr.models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr', '0022_auto_20170201_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='unix_username',
            field=models.CharField(default=supervisr.models.get_random_string, editable=False, max_length=10),
        ),
    ]
