# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 22:22
from __future__ import unicode_literals

from django.db import migrations


def create_settings(apps, schema_editor):
    Setting = apps.get_model('supervisr', 'Setting')
    settings = {
        'supervisr:banner:enabled': False,
        'supervisr:banner:message': '',
        'supervisr:banner:level': 'info',
        'supervisr:branding:icon': '',
    }
    for key, value in settings.items():
        Setting.objects.get_or_create(
            key=key,
            defaults={'value': value})

class Migration(migrations.Migration):

    dependencies = [
        ('supervisr', '0024_auto_20170222_1701'),
    ]

    operations = [
        migrations.RunPython(create_settings),
    ]
