from __future__ import unicode_literals
from django.db import models
from django.utils.translation import ugettext as _

class Product(object):
    product_id = models.AutoField(primary_key=True)
    name = models.TextField()
    slug = models.TextField()
    price = models.DecimalField()

class ServerProduct(Product):
    ips = models.ManyToManyField(IPAddress)
    # This is just a wrapper class to seperate server Products

class RootVPServerProduct(ServerProduct, models.Model):
    vcpus = models.IntegerField(description = _("Amount of CPU Cores"))
    vram = models.IntegerField(description = _("Amount of RAM (in GB)"))
    vhdd = models.IntegerField(description = _("Amount of HDD/SDD (in GB)"))
    is_flash = models.IntegerField(default=True, description=_("True if vhdd is on an SSD"))

class IPAddress(models.Model):
    ipaddress_id = models.AutoField(primary_key=True)
    address = models.GenericIPAddressField()
    #server = models.ForeignField(ServerProduct) this is generated by