# Generated by Django 2.1.1 on 2018-09-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_mod_provider_nix_dns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
