# Generated by Django 2.1.7 on 2019-03-18 18:46

import django.db.models.deletion
from django.db import migrations, models

import supervisr.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supervisr_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibCloudCredentials',
            fields=[
                ('basecredential_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supervisr_core.BaseCredential')),
                ('key', supervisr.core.fields.EncryptedField()),
                ('secret', supervisr.core.fields.EncryptedField(blank=True, default=None, null=True)),
                ('provider', models.TextField(choices=[('DNS', [('auroradns', 'Auroradns'), ('buddyns', 'Buddyns'), ('cloudflare', 'Cloudflare'), ('digital_ocean', 'Digitalocean'), ('dnsimple', 'Dnsimple'), ('dnspod', 'Dnspod'), ('dummy', 'Dummy'), ('durabledns', 'Durabledns'), ('gandi', 'Gandi'), ('godaddy', 'Godaddy'), ('google', 'Google'), ('hostvirtual', 'Hostvirtual'), ('linode', 'Linode'), ('liquidweb', 'Liquidweb'), ('luadns', 'Luadns'), ('nfsn', 'Nfsn'), ('nsone', 'Nsone'), ('onapp', 'Onapp'), ('pointdns', 'Pointdns'), ('powerdns', 'Powerdns'), ('rackspace', 'Rackspace'), ('rackspace_uk', 'Rackspaceuk'), ('rackspace_us', 'Rackspaceus'), ('route53', 'Route53'), ('softlayer', 'Softlayer'), ('vultr', 'Vultr'), ('worldwidedns', 'Worldwidedns'), ('zerigo', 'Zerigo'), ('zonomi', 'Zonomi')])])),
                ('secure', models.BooleanField(default=True)),
                ('host', models.TextField(blank=True, default=None, null=True)),
                ('port', models.IntegerField(blank=True, default=None, null=True)),
                ('api_version', models.TextField(blank=True, default=None, null=True)),
                ('region', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('supervisr_core.basecredential',),
        ),
    ]
