# Generated by Django 2.0.7 on 2018-07-21 07:38

from django.db import migrations

import supervisr.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_mod_provider_libcloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libcloudcredentials',
            name='secret',
            field=supervisr.core.fields.EncryptedField(blank=True, default=None, null=True),
        ),
    ]
