# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 22:22
from __future__ import unicode_literals

from django.db import migrations


def create_settings(apps, schema_editor):
    Setting = apps.get_model('core', 'Setting')
    settings = {
        'supervisr:ldap:enabled': False,
        'supervisr:ldap:server': '',
        'supervisr:ldap:base': '',
        'supervisr:ldap:create_base': '',
        'supervisr:ldap:bind:user': '',
        'supervisr:ldap:bind:pass': '',
        'supervisr:ldap:domain': '',
    }
    for key, value in settings.items():
        Setting.objects.get_or_create(
            key=key,
            defaults={'value': value})

class Migration(migrations.Migration):

    dependencies = [
        ('ldap', '0003_auto_20170220_2121'),
    ]

    operations = [
        migrations.RunPython(create_settings),
    ]
