# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 17:43
from __future__ import unicode_literals

from django.db import migrations


def create_settings(apps, schema_editor):
    Setting = apps.get_model('core', 'Setting')
    settings = {
        'mod:ldap:enabled': False,
        'mod:ldap:server': '',
        'mod:ldap:base': '',
        'mod:ldap:create_base': '',
        'mod:ldap:bind:user': '',
        'mod:ldap:bind:pass': '',
        'mod:ldap:domain': '',
    }
    for key, value in settings.items():
        Setting.objects.get_or_create(
            key=key,
            defaults={'value': value})

class Migration(migrations.Migration):

    dependencies = [
        ('ldap', '0006_remove_ldapmodification__purgeable'),
    ]

    operations = [
        migrations.RunPython(create_settings),
    ]
