#!/bin/bash

set -e

. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/postinst.mysql

# you can set the default database encoding to something else
dbc_mysql_createdb_encoding="UTF8"
dbc_generate_include=sh:/etc/supervisr/database-config
dbc_go supervisr "$@"

if [ -z "`getent group supervisr`" ]; then
  addgroup --quiet --system supervisr
fi
if [ -z "`getent passwd supervisr`" ]; then
  echo " * Creating user and group supervisr..."
  adduser --quiet --system --home /usr/share/supervisr --shell /bin/false --ingroup supervisr --disabled-password --disabled-login --gecos "Supervisr User" supervisr
fi
if [ ! -f '/etc/supervisr/secret_key' ]; then
  echo " * Generating Secret Key"
  supervisr-ctl supervisr.generate-secret-key > /etc/supervisr/secret_key 2> /dev/null
fi
rm -f /usr/share/supervisr/supervisr/local_settings.py
chown -R supervisr: /var/log/supervisr/
chown -R supervisr: /usr/share/supervisr/
chown -R supervisr: /etc/supervisr/
chmod 440 /etc/supervisr/secret_key
echo " * Running Database Migration"
supervisr-ctl utils.migrate

#DEBHELPER#

