# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccpanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servercpu',
            old_name='cores',
            new_name='physical_cores',
        ),
        migrations.AddField(
            model_name='servercpu',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servernic',
            name='ips',
            field=models.ManyToManyField(blank=True, null=True, to='ccpanel.IPAddress'),
        ),
    ]
