BBBBBBB BBBBBBBBBBB

BBBB BBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Login') XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
        FFFFFF
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXX gettext(u'Login') XXXXXXXXX
      XXXXXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXX gettext(u"Don't have an account yet?") XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXX gettext(u'Sign up here!') XXXX
    XXXXXX
  XXXXXX
XXXXXX
BBBBBBBB

