# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr', '0002_auto_20161231_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='management_url',
            field=models.URLField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
