# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr', '0018_product_ldap_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='destination_user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='source_user',
        ),
        migrations.AddField(
            model_name='event',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='remote_ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AddField(
            model_name='event',
            name='remote_ip_rdns',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='send_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
