# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 15:02
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import migrations

from ..models import get_system_user


def update_system_user(apps, schema_editor):
    system_user = User.objects.get(pk=get_system_user())
    system_user.is_superuser = True
    system_user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('supervisr', '0019_auto_20170118_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='domain_name',
        ),
        migrations.RunPython(
            code=update_system_user,
        ),
    ]
