# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 11:27
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ('supervisr', '0027_auto_20170325_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductExtension',
            fields=[
                ('created', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product_extension_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='oauth2_application',
        ),
        migrations.CreateModel(
            name='ProductExtensionOAuth2',
            fields=[
                ('productextension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supervisr.ProductExtension')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('supervisr.productextension',),
        ),
        migrations.AddField(
            model_name='product',
            name='extensions',
            field=models.ManyToManyField(to='supervisr.ProductExtension'),
        ),
    ]
