# Generated by Django 2.0.2 on 2018-02-24 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supervisr_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('useracquirable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supervisr_core.UserAcquirable')),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('supervisr_core.useracquirable',),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('useracquirable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supervisr_core.UserAcquirable')),
                ('name', models.TextField()),
                ('type', models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('AFSDB', 'AFSDB'), ('APL', 'APL'), ('CAA', 'CAA'), ('CDNSKEY', 'CDNSKEY'), ('CDS', 'CDS'), ('CERT', 'CERT'), ('CNAME', 'CNAME'), ('DHCID', 'DHCID'), ('DLV', 'DLV'), ('DNAME', 'DNAME'), ('DNSKEY', 'DNSKEY'), ('DS', 'DS'), ('HIP', 'HIP'), ('IPSECKEY', 'IPSECKEY'), ('KEY', 'KEY'), ('KX', 'KX'), ('LOC', 'LOC'), ('MX', 'MX'), ('NAPTR', 'NAPTR'), ('NS', 'NS'), ('NSEC', 'NSEC'), ('NSEC3', 'NSEC3'), ('NSEC3PARAM', 'NSEC3PARAM'), ('OPENPGPKEY', 'OPENPGPKEY'), ('PTR', 'PTR'), ('RRSIG', 'RRSIG'), ('RP', 'RP'), ('SIG', 'SIG'), ('SOA', 'SOA'), ('SRV', 'SRV'), ('SSHFP', 'SSHFP'), ('TA', 'TA'), ('TKEY', 'TKEY'), ('TLSA', 'TLSA'), ('TSIG', 'TSIG'), ('TXT', 'TXT'), ('URI', 'URI')], max_length=10)),
                ('content', models.TextField()),
                ('ttl', models.IntegerField(default=3600)),
                ('priority', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('supervisr_core.useracquirable',),
        ),
        migrations.CreateModel(
            name='ResourceSet',
            fields=[
                ('useracquirable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supervisr_core.UserAcquirable')),
                ('name', models.TextField()),
                ('resource', models.ManyToManyField(blank=True, to='supervisr_dns.Resource')),
            ],
            options={
                'abstract': False,
            },
            bases=('supervisr_core.useracquirable',),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('useracquirable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='supervisr_core.UserAcquirable')),
                ('provideracquirable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supervisr_core.ProviderAcquirable')),
                ('enabled', models.BooleanField(default=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisr_core.Domain')),
                ('soa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisr_dns.Resource')),
            ],
            options={
                'abstract': False,
            },
            bases=('supervisr_core.provideracquirable', 'supervisr_core.useracquirable'),
        ),
        migrations.AddField(
            model_name='record',
            name='record_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisr_dns.Zone'),
        ),
        migrations.AddField(
            model_name='record',
            name='resource_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisr_dns.ResourceSet'),
        ),
    ]
