# Generated by Django 2.1.1 on 2018-09-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_dns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reversezone',
            name='soa_mname',
            field=models.TextField(help_text="Primary Nameserver's Address"),
        ),
        migrations.AlterField(
            model_name='reversezone',
            name='soa_rname',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='zone',
            name='soa_mname',
            field=models.TextField(help_text="Primary Nameserver's Address"),
        ),
        migrations.AlterField(
            model_name='zone',
            name='soa_rname',
            field=models.EmailField(max_length=254),
        ),
    ]
