# Generated by Django 2.1.1 on 2018-09-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_dns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setrecord',
            name='records',
            field=models.ManyToManyField(blank=True, related_name='set', to='supervisr_dns.BaseRecord'),
        ),
    ]
