# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 19:29
from __future__ import unicode_literals

from django.db import migrations

from supervisr.core.models import get_system_user


def create_module(apps, schema_editor):
    PuppetModule = apps.get_model('supervisr/puppet', 'PuppetModule')
    User = apps.get_model('auth', 'User')
    system_user = User.objects.get(pk=get_system_user())

    PuppetModule.objects.get_or_create(
        name='supervisr_dns',
        owner=system_user,
        source_path='supervisr/dns/server/config/')

class Migration(migrations.Migration):

    dependencies = [
        ('supervisr/puppet', '0004_puppetmodule_source_path'),
        ('supervisr/dns', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_module),
    ]
