# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_dns', '0002_auto_20170814_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('AFSDB', 'AFSDB'), ('APL', 'APL'), ('CAA', 'CAA'), ('CDNSKEY', 'CDNSKEY'), ('CDS', 'CDS'), ('CERT', 'CERT'), ('CNAME', 'CNAME'), ('DHCID', 'DHCID'), ('DLV', 'DLV'), ('DNAME', 'DNAME'), ('DNSKEY', 'DNSKEY'), ('DS', 'DS'), ('HIP', 'HIP'), ('IPSECKEY', 'IPSECKEY'), ('KEY', 'KEY'), ('KX', 'KX'), ('LOC', 'LOC'), ('MX', 'MX'), ('NAPTR', 'NAPTR'), ('NS', 'NS'), ('NSEC', 'NSEC'), ('NSEC3', 'NSEC3'), ('NSEC3PARAM', 'NSEC3PARAM'), ('OPENPGPKEY', 'OPENPGPKEY'), ('PTR', 'PTR'), ('RRSIG', 'RRSIG'), ('RP', 'RP'), ('SIG', 'SIG'), ('SOA', 'SOA'), ('SRV', 'SRV'), ('SSHFP', 'SSHFP'), ('TA', 'TA'), ('TKEY', 'TKEY'), ('TLSA', 'TLSA'), ('TSIG', 'TSIG'), ('TXT', 'TXT'), ('URI', 'URI')], max_length=10),
        ),
    ]
