# Generated by Django 2.0.2 on 2018-02-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_dns', '0004_record_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
