# Generated by Django 2.1.1 on 2018-09-22 10:11

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_mod_auth_ldap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ldapmodification',
            name='ldap_moddification_id',
        ),
        migrations.AddField(
            model_name='ldapmodification',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
