# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 11:42
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr/core', '0028_auto_20170325_1227'),
        ('supervisr/mod/auth/ldap', '0004_add_ldap_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductExtensionLDAP',
            fields=[
                ('productextension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supervisr/core.ProductExtension')),
                ('ldap_group', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('supervisr/core.productextension',),
        ),
    ]
