# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldap', '0005_productextensionldap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ldapmodification',
            name='_purgeable',
        ),
    ]
