# This is the default configuration file
log:
  level:
    console: DEBUG
    file: DEBUG
  syslog:
    host: 127.0.0.1
    port: 514
  file: /dev/null
email:
  host: localhost
  port: 25
  user: ''
  password: ''
  use_tls: false
  use_ssl: false
  from: supervisr <supervisr@domain.tld>
sentry: ''
footer:
  # - text: ''
  #   view: ''
  #   url: ''
secret_key: _k*@6h2u2@q-dku57hhgzb7tnx*ba9wodcb^s9g0j59@=y(@_o
debug: true
domains:
  - localhost
timezone: UTC
redis: localhost
installed_apps:
  - supervisr.puppet.apps.SupervisrPuppetConfig
  - supervisr.dns.apps.SupervisrDNSConfig
  - supervisr.mod.provider.nix_dns.apps.SupervisrModProviderNixDNSConfig
  - supervisr.mod.provider.debug.apps.SupervisrModProviderDebugConfig
  - supervisr.mail.apps.SupervisrMailConfig
  - supervisr.static.apps.SupervisrStaticConfig
  - supervisr.mod.web_proxy.apps.SupervisrModWebProxyConfig
  - supervisr.mod.beacon.apps.SupervisrModBeaconConfig
  - supervisr.mod.auth.ldap.apps.SupervisrModAuthLDAPConfig
  - supervisr.mod.auth.saml.idp.apps.SupervisrModAuthSAMLProvider
  - supervisr.mod.auth.oauth.provider.apps.SupervisrModAuthOAuthProviderConfig
  - supervisr.mod.auth.oauth.client.apps.SupervisrModAuthOAuthClientConfig
  - supervisr.mod.tfa.apps.SupervisrModTFAConfig
  - supervisr.mod.stats.influx.apps.SupervisrModStatInfluxConfig
  - supervisr.mod.provider.libcloud.apps.SupervisrModProviderLibcloud
