# This is the default configuration file
databases:
  default:
    engine: 'django.db.backends.sqlite3'
    name: 'supervisr_test'
log:
  level:
    console: DEBUG
    file: DEBUG
  syslog:
    host: 127.0.0.1
    port: 514
  file:
    web: /dev/null
    task-runner: /dev/null
    task-scheduler: /dev/null
    task-monitor: /dev/null
email:
  host: localhost
  port: 25
  user: ''
  password: ''
  use_tls: false
  use_ssl: false
  from: supervisr <supervisr@domain.tld>
sentry: ''
http:
  default:
    listen: 0.0.0.0
    port: 8000
    threads: 30
footer:
  # - text: ''
  #   view: ''
  #   url: ''
secret_key: _k*@6h2u2@q-dku57hhgzb7tnx*ba9wodcb^s9g0j59@=y(@_o
debug: true
domains:
  - localhost
timezone: UTC
redis: localhost
installed_apps:
  - supervisr.puppet
  - supervisr.dns
  - supervisr.provider.nix_dns
  - supervisr.provider.debug
  - supervisr.mail
  - supervisr.provider.libcloud
