# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailaccount',
            name='domain_mail',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='supervisr_mail.MailDomain'),
            preserve_default=False,
        ),
    ]
