# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 21:10
from __future__ import unicode_literals

from django.db import migrations, models

def update_raw(apps, schema_editor):
    MailDomain = apps.get_model('supervisr_mail', 'MailDomain')
    MailAccount = apps.get_model('supervisr_mail', 'MailAccount')

    [x.save() for x in MailDomain.objects.all()]
    [x.save() for x in MailAccount.objects.all()]

class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_mail', '0002_mailaccount_domain_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailaccount',
            name='domain_raw',
            field=models.TextField(blank=True, help_text='This field is automatically generatedby Django to make queries easier.'),
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='email_raw',
            field=models.TextField(blank=True, help_text='This field is automatically generatedby Django to make queries easier.'),
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='is_catchall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maildomain',
            name='domain_raw',
            field=models.TextField(blank=True, help_text='This field is automatically generatedby Django to make queries easier.'),
        ),
        migrations.RunPython(update_raw),
    ]
