# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import supervisr.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPModification',
            fields=[
                ('_purgeable', models.BooleanField(default=False)),
                ('ldap_moddification_id', models.AutoField(primary_key=True, serialize=False)),
                ('dn', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('MODIFY_ADD', 'MODIFY_ADD'), ('MODIFY_DELETE', 'MODIFY_DELETE'), ('MODIFY_REPLACE', 'MODIFY_REPLACE'), ('MODIFY_INCREMENT', 'MODIFY_INCREMENT')], max_length=17)),
                ('data', supervisr.fields.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
