# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 12:17
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('ipaddress_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Product')),
                ('ram', models.IntegerField()),
                ('is_virtual', models.BooleanField(default=True)),
                ('is_managed', models.BooleanField(default=True)),
            ],
            bases=('core.product',),
        ),
        migrations.CreateModel(
            name='ServerCPU',
            fields=[
                ('cpu_id', models.AutoField(primary_key=True, serialize=False)),
                ('physical_cores', models.IntegerField()),
                ('smt', models.BooleanField()),
                ('frequency', models.IntegerField(default=0)),
                ('make', models.TextField()),
                ('model', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServerDrive',
            fields=[
                ('drive_id', models.AutoField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('make', models.TextField()),
                ('model', models.TextField()),
                ('rpm', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServerNIC',
            fields=[
                ('nic_id', models.AutoField(primary_key=True, serialize=False)),
                ('speed', models.IntegerField()),
                ('ips', models.ManyToManyField(blank=True, to='server.IPAddress')),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='cpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.ServerCPU'),
        ),
        migrations.AddField(
            model_name='server',
            name='drives',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.ServerDrive'),
        ),
        migrations.AddField(
            model_name='server',
            name='nics',
            field=models.ManyToManyField(to='server.ServerNIC'),
        ),
    ]
