#!/bin/bash

SUPERVISR_PACKAGED=false

# Check if this file is a symlink, if so, read real base dir
BASE_DIR=$(dirname $(readlink -f ${BASH_SOURCE[0]} 2> /dev/null) 2> /dev/null)
if [ $? -eq 0 ] && [ "$BASE_DIR" != $(pwd)  ]; then
	cd $BASE_DIR
	SUPERVISR_PACKAGED=true
fi

export SUPERVISR_PACKAGED

if [ "$1" == "" ]; then
	# Run --list if no arguments are passed
	COMMAND="invoke --list"
else
	# Otherwise pass arguments
	COMMAND="invoke $@"
fi

if [ $SUPERVISR_PACKAGED == true ]; then
	if [ "$(id -u)" != "0" ]; then
		echo "This script must be run as root" 1>&2
		exit 1
	fi
	/bin/su -s /bin/bash -c "cd $BASE_DIR && source env/bin/activate && $COMMAND && deactivate" supervisr
else
	cd $BASE_DIR
	source env/bin/activate
	$COMMAND
	deactivate
fi
