# Generated by Django 2.1.1 on 2018-09-25 10:28

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import supervisr.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAccess',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('access_token', supervisr.core.fields.EncryptedField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('ui_name', models.TextField(default='')),
                ('request_token_url', models.CharField(blank=True, max_length=255)),
                ('authorization_url', models.CharField(max_length=255)),
                ('access_token_url', models.CharField(max_length=255)),
                ('profile_url', models.CharField(max_length=255)),
                ('consumer_key', supervisr.core.fields.EncryptedField(blank=True, default=None, null=True)),
                ('consumer_secret', supervisr.core.fields.EncryptedField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='accountaccess',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisr_mod_auth_oauth_client.Provider'),
        ),
        migrations.AddField(
            model_name='accountaccess',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='accountaccess',
            unique_together={('identifier', 'provider')},
        ),
    ]
