# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 10:52
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import supervisr.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('access_token', supervisr.core.fields.EncryptedField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('request_token_url', models.CharField(blank=True, max_length=255)),
                ('authorization_url', models.CharField(max_length=255)),
                ('access_token_url', models.CharField(max_length=255)),
                ('profile_url', models.CharField(max_length=255)),
                ('consumer_key', supervisr.core.fields.EncryptedField(blank=True, default=None, null=True)),
                ('consumer_secret', supervisr.core.fields.EncryptedField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='accountaccess',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisr/mod/auth/oauth/client.Provider'),
        ),
        migrations.AddField(
            model_name='accountaccess',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='accountaccess',
            unique_together=set([('identifier', 'provider')]),
        ),
    ]
