# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_mod_auth_oauth_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='ui_name',
            field=models.TextField(default=''),
        ),
    ]
