# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 16:27
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_core', '0052_auto_20170726_1515'),
        ('supervisr_static', '0003_auto_20170709_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPage',
            fields=[
                ('staticpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supervisr_static.StaticPage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisr_core.Product')),
            ],
            options={
                'abstract': False,
            },
            bases=('supervisr_static.staticpage',),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='language',
            field=models.CharField(default='en', max_length=7),
        ),
    ]
