# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_static', '0004_auto_20170728_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='staticpage',
            unique_together=set([('slug', 'language')]),
        ),
    ]
