# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr/web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webdomain',
            name='custom_config',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='webdomain',
            name='root',
            field=models.TextField(default='/'),
        ),
    ]
