# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr/web', '0001_initial'),
    ]

    run_before = [
        ('supervisr/core', '0061_auto_20171118_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webdomain',
            name='profile',
        ),
    ]
