# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 13:38
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0045_auto_20170706_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamecheapCredentials',
            fields=[
                ('basecredential_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseCredential')),
                ('api_key', models.TextField()),
                ('api_user', models.TextField()),
                ('username', models.TextField()),
                ('sandbox', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.basecredential',),
        ),
    ]
