# Generated by Django 2.1.7 on 2019-03-18 18:45

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import supervisr.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCredential',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderAcquirable',
            fields=[
                ('provider_acquirable_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderAcquirableRelationship',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisr_core.ProviderAcquirable')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderAcquirableSingle',
            fields=[
                ('provider_acquirable_single_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255)),
                ('namespace', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('task_uuid', models.UUIDField()),
                ('invoker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAcquirable',
            fields=[
                ('user_acquirable_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAcquirableRelationship',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='APIKeyCredential',
            fields=[
                ('basecredential_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supervisr_core.BaseCredential')),
                ('api_key', supervisr.core.fields.EncryptedField()),
            ],
            options={
                'abstract': False,
            },
            bases=('supervisr_core.basecredential',),
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('useracquirable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='domains', to='supervisr_core.UserAcquirable')),
                ('provideracquirablesingle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='domains', to='supervisr_core.ProviderAcquirableSingle')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('domain_name', models.CharField(max_length=253, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'default_related_name': 'domains',
            },
            bases=('supervisr_core.provideracquirablesingle', 'supervisr_core.useracquirable', models.Model),
        ),
        migrations.CreateModel(
            name='EmptyCredential',
            fields=[
                ('basecredential_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supervisr_core.BaseCredential')),
            ],
            options={
                'abstract': False,
            },
            bases=('supervisr_core.basecredential',),
        ),
        migrations.CreateModel(
            name='ProviderInstance',
            fields=[
                ('useracquirable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='supervisr_core.UserAcquirable')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('provider_path', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('supervisr_core.useracquirable', models.Model),
        ),
        migrations.CreateModel(
            name='UserPasswordCredential',
            fields=[
                ('basecredential_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supervisr_core.BaseCredential')),
                ('username', models.TextField()),
                ('password', supervisr.core.fields.EncryptedField()),
            ],
            options={
                'abstract': False,
            },
            bases=('supervisr_core.basecredential',),
        ),
        migrations.CreateModel(
            name='UserPasswordServerCredential',
            fields=[
                ('basecredential_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supervisr_core.BaseCredential')),
                ('username', models.TextField()),
                ('password', supervisr.core.fields.EncryptedField()),
                ('server', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('supervisr_core.basecredential',),
        ),
        migrations.AddField(
            model_name='useracquirablerelationship',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisr_core.UserAcquirable'),
        ),
        migrations.AddField(
            model_name='useracquirablerelationship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useracquirable',
            name='users',
            field=models.ManyToManyField(through='supervisr_core.UserAcquirableRelationship', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='setting',
            unique_together={('key', 'namespace')},
        ),
        migrations.AddField(
            model_name='basecredential',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='useracquirablerelationship',
            unique_together={('user', 'model')},
        ),
        migrations.AddField(
            model_name='providerinstance',
            name='credentials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisr_core.BaseCredential'),
        ),
        migrations.AddField(
            model_name='provideracquirablesingle',
            name='provider_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisr_core.ProviderInstance'),
        ),
        migrations.AddField(
            model_name='provideracquirablerelationship',
            name='provider_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisr_core.ProviderInstance'),
        ),
        migrations.AddField(
            model_name='provideracquirable',
            name='providers',
            field=models.ManyToManyField(blank=True, through='supervisr_core.ProviderAcquirableRelationship', to='supervisr_core.ProviderInstance'),
        ),
        migrations.AlterUniqueTogether(
            name='basecredential',
            unique_together={('owner', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='provideracquirablerelationship',
            unique_together={('provider_instance', 'model')},
        ),
    ]
