# Generated by Django 2.0.2 on 2018-02-24 23:11

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerinstance',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
