# Generated by Django 2.0.6 on 2018-06-16 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_core', '0002_setup'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLProductExtension',
            fields=[
                ('productextension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supervisr_core.ProductExtension')),
                ('url', models.URLField()),
                ('role', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('supervisr_core.productextension',),
        ),
    ]
