# Generated by Django 2.0.2 on 2018-02-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_core', '0002_providerinstance_uuid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='provideracquirablerelationship',
            unique_together={('provider_instance', 'model')},
        ),
        migrations.AlterUniqueTogether(
            name='useracquirablerelationship',
            unique_together={('user', 'model')},
        ),
    ]
