# Generated by Django 2.0.6 on 2018-06-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_core', '0003_urlproductextension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
