# Generated by Django 2.0.2 on 2018-02-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_core', '0003_auto_20180225_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provideracquirable',
            name='providers',
            field=models.ManyToManyField(blank=True, through='supervisr_core.ProviderAcquirableRelationship', to='supervisr_core.ProviderInstance'),
        ),
    ]
