# Generated by Django 2.1.1 on 2018-09-12 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_core', '0004_auto_20180617_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provideracquirablesingle',
            old_name='provider_acquirable_Single_id',
            new_name='provider_acquirable_single_id',
        ),
        migrations.AlterField(
            model_name='domain',
            name='provideracquirablesingle_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='domains', serialize=False, to='supervisr_core.ProviderAcquirableSingle', to_field='provider_acquirable_single_id'),
        ),
    ]
