# Generated by Django 2.0.2 on 2018-03-01 17:13

from django.conf import settings
from django.db import migrations


def create_user(apps, schema_editor):
    User = apps.get_model('supervisr_core', 'User')
    system_user = User.objects.get_or_create(
        username=settings.SYSTEM_USER_NAME,
        is_active=False,
        is_staff=False,
        is_superuser=True,
        first_name='System',
        defaults={'email': 'root@localhost'})

def create_puppet_module(apps, schema_editor):
    try:
        PuppetModule = apps.get_model('supervisr_puppet', 'PuppetModule')
        User = apps.get_model('supervisr_core', 'User')
        system_user = User.objects.get(pk=get_system_user())

        PuppetModule.objects.get_or_create(
            name='supervisr_core',
            owner=system_user,
            source_path='supervisr/core/server/config/')
    except LookupError:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_core', '0005_stagedproviderchange'),
    ]

    operations = [
        migrations.RunPython(create_user),
        migrations.RunPython(create_puppet_module)
    ]
