# Generated by Django 2.1.1 on 2018-09-18 16:38

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_core', '0006_auto_20180912_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountconfirmation',
            old_name='account_confirmation_id',
            new_name='uuid',
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
