# Generated by Django 2.1.1 on 2018-09-16 11:15

import uuid

import django.db.models.deletion
from django.db import migrations, models

import supervisr.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0008_auto_20171203_2001'),
        ('supervisr_core', '0006_auto_20180912_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='CA',
            fields=[
                ('useracquirable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='supervisr_core.UserAcquirable')),
                ('certificateauthority_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='django_ca.CertificateAuthority')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('django_ca.certificateauthority', 'supervisr_core.useracquirable', models.Model),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('useracquirable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='supervisr_core.UserAcquirable')),
                ('certificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='django_ca.Certificate')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('django_ca.certificate', 'supervisr_core.useracquirable', models.Model),
        ),
        migrations.CreateModel(
            name='CertificateKeyPair',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisr_core.Certificate')),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('useracquirable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='supervisr_core.UserAcquirable')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('private_key', supervisr.core.fields.EncryptedField()),
            ],
            options={
                'abstract': False,
            },
            bases=('supervisr_core.useracquirable', models.Model),
        ),
        migrations.RenameField(
            model_name='accountconfirmation',
            old_name='account_confirmation_id',
            new_name='uuid',
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='certificatekeypair',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisr_core.Key'),
        ),
        migrations.AlterUniqueTogether(
            name='certificatekeypair',
            unique_together={('certificate', 'key')},
        ),
    ]
