# Generated by Django 2.0.2 on 2018-03-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_core', '0006_setup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproductrelationship',
            name='product',
        ),
        migrations.RemoveField(
            model_name='userproductrelationship',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProductRelationship',
        ),
    ]
