# Generated by Django 2.0.2 on 2018-03-07 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_core', '0007_auto_20180302_1849'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InternalCredential',
            new_name='EmptyCredential',
        ),
    ]
