# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 12:00
from __future__ import unicode_literals

from django.db import migrations, models

import supervisr.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr/core', '0008_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servernic',
            name='ips',
        ),
        migrations.RemoveField(
            model_name='serverproduct',
            name='cpus',
        ),
        migrations.RemoveField(
            model_name='serverproduct',
            name='drives',
        ),
        migrations.RemoveField(
            model_name='serverproduct',
            name='nics',
        ),
        migrations.RemoveField(
            model_name='serverproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unix_userid',
            field=models.IntegerField(default=supervisr.core.models.get_userid),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unix_username',
            field=models.CharField(default=supervisr.core.models.get_random_string, editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.DeleteModel(
            name='IPAddress',
        ),
        migrations.DeleteModel(
            name='ServerCPU',
        ),
        migrations.DeleteModel(
            name='ServerDrive',
        ),
        migrations.DeleteModel(
            name='ServerNIC',
        ),
        migrations.DeleteModel(
            name='ServerProduct',
        ),
    ]
