# Generated by Django 2.0.3 on 2018-03-22 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_core', '0008_auto_20180307_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='revision',
        ),
    ]
