# Generated by Django 2.0.3 on 2018-04-02 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_core', '0010_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagedproviderchange',
            name='provider_instance',
        ),
        migrations.DeleteModel(
            name='StagedProviderChange',
        ),
    ]
