# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostedapplicationproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='revision',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='HostedApplicationProduct',
        ),
    ]
