# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 16:26
from __future__ import unicode_literals

from django.db import migrations


def update_settings(apps, schema_editor):
    Setting = apps.get_model('supervisr/core', 'Setting')
    settings = {
        'core:password:filter:description': 'Minimum 8 characters at least 1 Uppercase Alphabet, 1 Lowercase Alphabet, 1 Number and 1 Special Character',
        'core:password:filter': "^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[$@$!%*?&])[A-Za-z\d$@$!%*?&]{8,}",
    }
    for key, value in settings.items():
        Setting.objects.get_or_create(
            key=key,
            defaults={'value': value})

class Migration(migrations.Migration):

    dependencies = [
        ('supervisr/core', '0016_create_settings_2'),
    ]

    operations = [
        migrations.RunPython(update_settings),
    ]
