# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20170202_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='action_parmas_json',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='action_view',
            field=models.TextField(blank=True),
        ),
    ]
