# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 10:03
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_core', '0026_auto_20170323_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ldap_group',
        ),
    ]
