# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 11:27
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr/core', '0027_auto_20170325_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductExtension',
            fields=[
                ('created', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product_extension_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='extensions',
            field=models.ManyToManyField(to='supervisr/core.ProductExtension'),
        ),
    ]
