# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_core', '0028_auto_20170325_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='news_subscribe',
            field=models.BooleanField(default=False),
        ),
    ]
