# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_userprofile_news_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='_purgeable',
            field=models.BooleanField(default=False),
        ),
    ]
