# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 11:06
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models

from supervisr.core.models import make_username


def update_username(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('supervisr/core', 'UserProfile')
    for up in UserProfile.objects.all():
        up.username = up.user.email
        up.unix_username = make_username(up.username)
        up.save()

class Migration(migrations.Migration):

    dependencies = [
        ('supervisr/core', '0032_auto_20170423_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.RunPython(update_username),
    ]
