# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 12:42
from __future__ import unicode_literals

from django.db import migrations, models

import supervisr.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='unix_username',
            field=models.CharField(default=supervisr.core.models.get_random_string, editable=False, max_length=32),
        ),
    ]
