# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20170604_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='crypt6_password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
