# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_core', '0035_userprofile_crypt6_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='productextension',
            name='extension_name',
            field=models.TextField(default=''),
        ),
    ]
