# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_core', '0036_productextension_extension_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='extensions',
            field=models.ManyToManyField(blank=True, to='supervisr_core.ProductExtension'),
        ),
    ]
