# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 08:25
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import supervisr.core.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0041_baseproviderinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='APIKeyCredential',
            fields=[
                ('basecredential_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseCredential')),
                ('api_key', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('core.basecredential',),
        ),
        migrations.CreateModel(
            name='UserPasswordCredential',
            fields=[
                ('basecredential_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseCredential')),
                ('username', models.TextField()),
                ('password', supervisr.core.fields.EncryptedField()),
            ],
            options={
                'abstract': False,
            },
            bases=('core.basecredential',),
        ),
        migrations.AddField(
            model_name='basecredential',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basecredential',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BaseProviderInstance'),
        ),
    ]
