# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 08:37
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20170706_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecredential',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='providerinstance',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='providerinstance',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='providerinstance',
            name='user_password',
        ),
        migrations.AddField(
            model_name='providerinstance',
            name='credentials',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.BaseCredential'),
            preserve_default=False,
        ),
    ]
