# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 08:39
from __future__ import unicode_literals

from django.db import migrations

import supervisr.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20170706_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeycredential',
            name='api_key',
            field=supervisr.core.fields.EncryptedField(),
        ),
    ]
