# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 11:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supervisr/core', '0044_auto_20170706_1039'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basecredential',
            unique_together=set([('owner', 'name')]),
        ),
    ]
