# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 14:01
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supervisr/core', '0046_auto_20170706_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='BaseProviderInstance',
            old_name='provider',
            new_name='provider_path',
        ),
        migrations.AddField(
            model_name='BaseProviderInstance',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
