# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 14:27
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20170706_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseproviderinstance',
            name='id',
        ),
        migrations.RemoveField(
            model_name='baseproviderinstance',
            name='owner',
        ),
        migrations.AddField(
            model_name='baseproviderinstance',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Product'),
            preserve_default=False,
        ),
    ]
