# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 09:21
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_product_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='registrar',
        ),
        migrations.AddField(
            model_name='domain',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.BaseProviderInstance'),
            preserve_default=False,
        ),
    ]
