# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_core', '0052_auto_20170726_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
