# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_core', '0054_auto_20170804_1941'),
        ('supervisr_core', '0053_product_auto_generated'),
    ]

    operations = [
    ]
