# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_merge_20170805_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='namespace',
            field=models.CharField(max_length=255, default=''),
        ),
    ]
