# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 17:43
from __future__ import unicode_literals

from django.db import migrations, models

NAMESPACE_MAP = {
    'core:': 'supervisr.core',
    'mail:': 'supervisr.mail',
    'mod:auth:saml:idp:': 'supervisr.mod.auth.saml.idp',
    'mod:ldap:': 'supervisr.mod.auth.ldap',
    'mod:stats:graphite': 'supervisr.mod.stats.graphite',
    'puppet:': 'supervisr.puppet',
}

def update_settings(apps, schema_editor):
    Setting = apps.get_model('supervisr/core', 'Setting')
    for set in Setting.objects.all():
        for key, value in NAMESPACE_MAP.items():
            if set.key.startswith(key):
                set.namespace = value
                set.key = set.key.replace(key, '')
                set.save()

class Migration(migrations.Migration):

    dependencies = [
        ('supervisr/core', '0056_setting_namespace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='setting',
            name='setting_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='setting',
            unique_together=set([('key', 'namespace')]),
        ),
        migrations.RunPython(update_settings),
    ]
