# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 19:12
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


def update_dummy_internal(apps, schema_editor):
    ProviderInstance = apps.get_model('supervisr_core', 'ProviderInstance')
    for pinst in ProviderInstance.objects.all():
        if pinst.provider_path == 'supervisr.core.providers.dummy.DummyBaseProvider':
            pinst.provider_path = 'supervisr.core.providers.internal.InternalBaseProvider'
            pinst.save()

class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_core', '0057_auto_20170818_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalCredential',
            fields=[
                ('basecredential_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supervisr_core.BaseCredential')),
            ],
            options={
                'abstract': False,
            },
            bases=('supervisr_core.basecredential',),
        ),
        migrations.RunPython(update_dummy_internal),
    ]
