# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 14:02
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import supervisr.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_internalcredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPasswordServerCredential',
            fields=[
                ('basecredential_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseCredential')),
                ('username', models.TextField()),
                ('password', supervisr.core.fields.EncryptedField()),
                ('server', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.basecredential',),
        ),
    ]
