# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_core', '0059_userpasswordservercredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='namespace',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
