# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 08:19
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_core', '0062_auto_20171202_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
