BBBB BBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
  XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXXXXXXXXXXXXXXXXXXXXX
    BBBBB BBBBBB
    BBBBBBBB
  XXXXXXX
  XXXXXX
    BBBBB BBBB
    BBBBBBBB
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX
XXXXXXX
