# Generated by Django 2.0.2 on 2018-03-02 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supervisr_core', '0007_auto_20180302_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductExtensionSAML2',
            fields=[
                ('productextension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supervisr_core.ProductExtension')),
            ],
            options={
                'abstract': False,
            },
            bases=('supervisr_core.productextension',),
        ),
        migrations.CreateModel(
            name='SAMLRemote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('acs_url', models.URLField()),
                ('processor_path', models.CharField(max_length=255)),
                ('skip_authorization', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productextensionsaml2',
            name='saml_remote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisr_mod_auth_saml_idp.SAMLRemote'),
        ),
    ]
