# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SAMLRemote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(unique=True)),
                ('acs_url', models.URLField()),
                ('processor_path', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
