# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr/mod/auth/saml/idp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samlremote',
            name='processor_path',
            field=models.CharField(max_length=255),
        ),
    ]
