# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_mod_auth_saml_idp', '0003_productextensionsaml2'),
    ]

    operations = [
        migrations.AddField(
            model_name='samlremote',
            name='skip_authorization',
            field=models.BooleanField(default=False),
        ),
    ]
