# Generated by Django 2.0.2 on 2018-02-27 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supervisr_core', '0004_auto_20180225_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('useracquirable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='supervisr_core.UserAcquirable')),
                ('provideracquirable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supervisr_core.ProviderAcquirable')),
                ('created', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('quota', models.BigIntegerField(default=0)),
                ('size', models.BigIntegerField(default=0)),
                ('password', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'abstract': False,
            },
            bases=('supervisr_core.provideracquirable', 'supervisr_core.useracquirable', models.Model),
        ),
        migrations.CreateModel(
            name='AccountAddressRelationship',
            fields=[
                ('useracquirable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supervisr_core.UserAcquirable')),
                ('created', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('can_send', models.BooleanField(default=True)),
                ('can_receive', models.BooleanField(default=True)),
                ('mail_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisr_mail.Account')),
            ],
            options={
                'abstract': False,
            },
            bases=('supervisr_core.useracquirable', models.Model),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('useracquirable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='supervisr_core.UserAcquirable')),
                ('provideracquirable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supervisr_core.ProviderAcquirable')),
                ('created', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('mail_address', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('supervisr_core.provideracquirable', 'supervisr_core.useracquirable', models.Model),
        ),
        migrations.CreateModel(
            name='Forwarder',
            fields=[
                ('useracquirable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='supervisr_core.UserAcquirable')),
                ('provideracquirable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supervisr_core.ProviderAcquirable')),
                ('created', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('destination_address', models.EmailField(max_length=254)),
                ('source_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisr_mail.Address')),
            ],
            options={
                'abstract': False,
            },
            bases=('supervisr_core.provideracquirable', 'supervisr_core.useracquirable', models.Model),
        ),
        migrations.CreateModel(
            name='MailDomain',
            fields=[
                ('useracquirable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='supervisr_core.UserAcquirable')),
                ('provideracquirable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supervisr_core.ProviderAcquirable')),
                ('created', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supervisr_core.Domain')),
            ],
            options={
                'abstract': False,
            },
            bases=('supervisr_core.provideracquirable', 'supervisr_core.useracquirable', models.Model),
        ),
        migrations.CreateModel(
            name='MailDomainAddressRelationship',
            fields=[
                ('useracquirable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supervisr_core.UserAcquirable')),
                ('created', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_catchall', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('mail_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisr_mail.Address')),
                ('mail_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisr_mail.MailDomain')),
            ],
            options={
                'abstract': False,
            },
            bases=('supervisr_core.useracquirable', models.Model),
        ),
        migrations.AddField(
            model_name='address',
            name='domains',
            field=models.ManyToManyField(through='supervisr_mail.MailDomainAddressRelationship', to='supervisr_mail.MailDomain'),
        ),
        migrations.AddField(
            model_name='accountaddressrelationship',
            name='mail_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisr_mail.Address'),
        ),
        migrations.AddField(
            model_name='account',
            name='addresses',
            field=models.ManyToManyField(through='supervisr_mail.AccountAddressRelationship', to='supervisr_mail.Address'),
        ),
    ]
