# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 19:47
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_mailaccount_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailForwarder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('destination', models.EmailField(max_length=254)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.MailAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
