# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_mail', '0010_auto_20170418_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailaccount',
            old_name='domain_mail',
            new_name='domain',
        ),
        migrations.RenameField(
            model_name='maildomain',
            old_name='domain_mail',
            new_name='domain',
        ),
    ]
