# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr_mail', '0011_auto_20170629_1737'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailForwarder',
            new_name='MailAlias',
        ),
    ]
