# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 12:47
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr/mail', '0013_maildomain_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maildomain',
            name='provider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='supervisr/core.ProviderInstance'),
        ),
    ]
