# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr/mail', '0014_auto_20170726_1447'),
        ('supervisr/mail', '0014_auto_20170717_0631'),
    ]

    operations = [
    ]
