# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisr/mail', '0015_merge_20170805_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='maildomain',
            name='destination',
            field=models.TextField(default='internal'),
        ),
    ]
