# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supervisr', '0010_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebDomain',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supervisr.Product')),
                ('root', models.TextField()),
                ('quota', models.BigIntegerField(default=0)),
                ('is_php_enabled', models.BooleanField(default=True)),
                ('custom_config', models.TextField()),
                ('domain_web', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supervisr.Domain')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisr.UserProfile')),
            ],
            bases=('supervisr.product',),
        ),
    ]
