# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 11:47
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supervisr_core', '0058_internalcredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPasswordServerCredential',
            fields=[
                ('userpasswordcredential_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supervisr_core.UserPasswordCredential')),
                ('server', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('supervisr_core.userpasswordcredential',),
        ),
    ]
